INSERT INTO activity VALUES(uuid(),'Natació - Infantil',24);
INSERT INTO activity VALUES(uuid(),'Dansa Creativa - Infantil',30);
INSERT INTO activity VALUES(uuid(),'Anglès (dimarts) - Infantil',18);
INSERT INTO activity VALUES(uuid(),'Capoeira - Infantil',10);
INSERT INTO activity VALUES(uuid(),'Psicomotricitat - Infantil',15);
INSERT INTO activity VALUES(uuid(),'Ioga - Infantil',10);
INSERT INTO activity VALUES(uuid(),'Circ - Infantil',10);
INSERT INTO activity VALUES(uuid(),'Anglès (dijous) - Infantil',18);
INSERT INTO activity VALUES(uuid(),'Escacs - Primària',30);
INSERT INTO activity VALUES(uuid(),'Modern Jazz - Primària',30);
INSERT INTO activity VALUES(uuid(),'Circ - Primària',10);
INSERT INTO activity VALUES(uuid(),'Capoeira - Primària',10);
INSERT INTO activity VALUES(uuid(),'Anglès - Primària',24);
INSERT INTO activity VALUES(uuid(),'Natació - Primària',24);
INSERT INTO activity VALUES(uuid(),'Ioga - Primària',10);